include:
  - PYE/compose.yaml

services:
  website:
    image: caddy:2.11.2-alpine
    hostname: website
    ports:
      - 8001:80
      - 8003:443
    volumes:
      - $PWD/website/:/srv

  curlsite:
    build: ./curl-padjokej.dev
    hostname: curlsite
    ports:
      - 8002:8002

  rythmo:
    build: ./pyrythmo
    hostname: rythmo
    ports:
      - "8080:8080"
    volumes:
      - rythmo_stats:/app/stats
  
  caddy:
    image: caddy:2.11.2-alpine
    hostname: caddy
    restart: unless-stopped
    ports:
      - "443:443"
      - "443:443/udp"
      - "80:80"
    volumes:
      - $PWD/caddy:/etc/caddy
      - caddy_data:/data

volumes:
  caddy_data:
  rythmo_stats:
